version: '3.8'

services:
  # Service Base de Données
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_net

  # Service Backend
  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_NAME: taskdb
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - internal_net

  # Service Frontend
  frontend:
    build: ./frontend
    ports:
      - "8083:80"
    depends_on:
      - backend
    networks:
      - internal_net

volumes:
  db_data:

networks:
  internal_net:
    driver: bridge